title:              SVTCHIVE
email:              ""
description:        시간과 공간에 구애받지 않는 세븐틴 저장소🗂️
author:             SVTCHIVE
baseurl:            ""
url:                "https://svtchive.kr"
enforce_ssl:        "www.svtchive.kr"

# Social Profiles
twitter_username:   SVTCHIVE
github_username:
facebook_username:
instagram_username:
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-188229767-1 # out your google-analytics code

# Build settings
markdown:           kramdown
permalink:          /:title
paginate:           10
paginate_path:      "/playlists/page:num"
plugins:
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
